spring:
  application:
    name: logologolab
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://logologolab-db.cfemommyi6vf.ap-northeast-2.rds.amazonaws.com:3306/logologolab?zeroDateTimeBehavior=CONVERT_TO_NULL
    username: admin
    password: logologolab1234

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100

server:
  tomcat:
    connection-timeout: 300000  # 300초 (5분)
    keep-alive-timeout: 300000
    threads:
      max: 200
  servlet:
    session:
      timeout: 30m
      cookie:
        secure: true
        same-site: none
  ssl:
    enabled: false

server.servlet.session.cookie:
  secure: true
  same-site: none

springdoc:
  swagger-ui:
    tags-sorter: alpha  # 태그를 알파벳(가나다/숫자) 순으로 정렬
    enabled: ${SWAGGER_UI_ENABLED:true}

jwt:
  secret-key: "6JH2ZOW311lZxgNpgNRph6utq8RSQ/YZoJnlmZ8dK5s="
  expiration: 86400000
  refresh-expiration: 604800000 # 7일 in ms

kakao:
  client-id: 90f50962e1aec28d9fb794503d4cb53b
  client-secret: LTWnEbEW6PloFHEJZQXJb6vfIw5x8lgl
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me

naver:
  client-id: _ogBa1roqTMqbIID5Qih
  client-secret: ZOlwTJJzoy
  token-uri: https://nid.naver.com/oauth2.0/token
  user-info-uri: https://openapi.naver.com/v1/nid/me

#S3 설정 전
cloud:
  aws:
    credentials:
      access-key: AKIA5IPMWWKSGPR5SZEB
      secret-key: 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
    region:
      static: ap-northeast-2  # 서울 리전
      auto: false

s3:
  bucket: logologolab-photo  # 만든 S3 버킷 이름

openai:
  api:
    key: ${OPENAI_API_KEY}